# Generated by Django 3.1.7 on 2021-02-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/doctors/')),
                ('methods', models.ManyToManyField(to='api.Method')),
            ],
        ),
        migrations.CreateModel(
            name='launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.dataprofile')),
            ],
        ),
        migrations.AddField(
            model_name='dataprofile',
            name='methods',
            field=models.ManyToManyField(to='api.Method'),
        ),
    ]
