# Generated by Django 3.1.7 on 2021-02-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_airtable',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(unique=True, upload_to='doctors/'),
        ),
    ]
