# Generated by Django 3.1.7 on 2021-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_airtable',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
