# Generated by Django 3.1.7 on 2021-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210224_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
