# Generated by Django 3.1.7 on 2021-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210225_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='data',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='dataProfile',
        ),
    ]
