# DJANGO KEY
SECRET_KEY = ''

# Postgres
POSTGRES_NAME = ''
POSTGRES_USER = ''
PASSWORD = ''
HOST = ''

# AIRTABLE
AIRTABLE_TABLE_NAME = 'Psychotherapists'
AIRTABLE_BASE_ID = ''
AIRTABLE_YOUR_API_KEY = ''
